In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/student_performance.csv')

In [ ]:
df.shape

(30, 13)

In [ ]:
df.head(10)

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023
5,1006,Meera Joshi,20,Female,Electronics,2,58,66,70,52,72,Pune,2023
6,1007,Kiran Kumar,21,Male,Civil,2,73,69,65,40,85,Bangalore,2023
7,1008,Divya Singh,19,Female,Computer Science,2,88,91,84,93,96,Lucknow,2023
8,1009,Rahul Mishra,20,Male,Mechanical,2,62,71,58,45,68,Varanasi,2023
9,1010,Ananya Das,19,Female,Computer Science,2,95,89,90,97,98,Kolkata,2023

In [ ]:
print(df.iloc[:, 4].shape)

(30,)

In [ ]:
print(df.columns.tolist())

['student_id', 'name', 'age', 'gender', 'department', 'semester', 'math_score', 'science_score', 'english_score', 'programming_score', 'attendance_percentage', 'city', 'admission_year']

In [ ]:
print(df.dtypes)

student_id                int64
name                     object
age                       int64
gender                   object
department               object
semester                  int64
math_score                int64
science_score             int64
english_score             int64
programming_score         int64
attendance_percentage     int64
city                     object
admission_year            int64
dtype: object

In [ ]:
df.describe()

,student_id,age,semester,math_score,science_score,english_score,programming_score,attendance_percentage,admission_year
count,30.000000,30.000000,30.0,30.000000,30.000000,30.000000,30.000000,30.000000,30.0
mean,1015.500000,19.733333,2.0,76.066667,77.833333,74.166667,67.600000,84.500000,2023.0
std,8.803408,0.739680,0.0,11.467896,8.554423,10.003735,21.041175,9.379913,0.0
min,1001.000000,19.000000,2.0,56.000000,61.000000,55.000000,38.000000,65.000000,2023.0
25%,1008.250000,19.000000,2.0,67.250000,71.250000,67.250000,49.250000,77.250000,2023.0
50%,1015.500000,20.000000,2.0,75.500000,78.000000,75.000000,66.000000,86.500000,2023.0
75%,1022.750000,20.000000,2.0,85.750000,83.750000,81.750000,88.750000,91.750000,2023.0
max,1030.000000,21.000000,2.0,95.000000,93.000000,90.000000,97.000000,98.000000,2023.0

In [ ]:
df.isnull().sum()

student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               0
science_score            0
english_score            0
programming_score        0
attendance_percentage    0
city                     0
admission_year           0
dtype: int64

If you meant to remove the entire column, you can use `df.drop(columns=['column_name'], inplace=True)`.

If you want to remove rows where a specific column has `NaN` values, you can use `df.dropna(subset=['column_name'], inplace=True)`.

In [ ]:
import numpy as np
df.loc[df.index[:5],'math_score']=np.nan
df.isna().sum()

student_id                0
name                      0
age                       0
gender                    0
department                0
semester                  0
math_score               20
science_score             0
english_score             0
programming_score         0
attendance_percentage     0
city                      0
admission_year            0
dtype: int64

student_id                0
name                      0
age                       0
gender                    0
department                0
semester                  0
math_score               20
science_score             0
english_score             0
programming_score         0
attendance_percentage     0
city                      0
admission_year            0
dtype: int64

In [ ]:
df.loc[0:4,'math_score']=None
df.isnull().sum()

student_id                0
name                      0
age                       0
gender                    0
department                0
semester                  0
math_score               20
science_score             0
english_score             0
programming_score         0
attendance_percentage     0
city                      0
admission_year            0
dtype: int64

In [ ]:
df['gender'].count()

np.int64(30)

In [ ]:
df['semester'].count()

np.int64(30)

In [ ]:
print(df['department'].unique())

print("------------------------------------------------------------------")

print(df['department'].value_counts)

['Computer Science' 'Electronics' 'Mechanical' 'Civil']
------------------------------------------------------------------
<bound method IndexOpsMixin.value_counts of 0     Computer Science
1     Computer Science
2          Electronics
3           Mechanical
4     Computer Science
5          Electronics
6                Civil
7     Computer Science
8           Mechanical
9     Computer Science
10         Electronics
11               Civil
12    Computer Science
13          Mechanical
14    Computer Science
15         Electronics
16               Civil
17    Computer Science
18          Mechanical
19    Computer Science
20         Electronics
21    Computer Science
22               Civil
23          Mechanical
24    Computer Science
25         Electronics
26    Computer Science
27               Civil
28          Mechanical
29    Computer Science
Name: department, dtype: object>

In [ ]:
high_attendance=df[df['attendance_percentage']<=75]
print(f"Students with attendance less than or equal to 75%:{len(high_attendance)}")
print(high_attendance[['name','department','attendance_percentage']])

Students with attendance less than or equal to 75%:7
             name        department  attendance_percentage
5     Meera Joshi       Electronics                     72
8    Rahul Mishra        Mechanical                     68
14    Ajay Tiwari  Computer Science                     75
16   Manoj Pandey             Civil                     65
20  Harish Pillai       Electronics                     74
22   Sanjay Dubey             Civil                     70
27  Sunita Pillai             Civil                     73

In [ ]:
df['total_score']=df['math_score']+df['science_score']+df['english_score']+df['programming_score']
top_student=df.loc[df['total_score'].idxmax()]
print("Top student:")
print(f"Name:{top_student['name']}")
print(f"Departmentr:{top_student['department']}")
print(f"Total Score:{top_student['total_score']}")
print(f"Attendance:{top_student['attendance_percentage']}%")

Top student:
Name:Ananya Das
Departmentr:Computer Science
Total Score:371.0
Attendance:98%